SELECT
    VISIT_DETAILS_ENHANCED_EDW.*,
    EMPLOYEE_TIER_5.*,
    CALENDAR.*
FROM ac_cloud.VISIT_DETAILS_ENHANCED_EDW AS VISIT_DETAILS_ENHANCED_EDW
LEFT JOIN AC_CLOUD_EDW.EMPLOYEE_TIER_5 AS EMPLOYEE_TIER_5
    ON VISIT_DETAILS_ENHANCED_EDW.TENANT_UUID = EMPLOYEE_TIER_5.TENANT_UUID
    AND EMPLOYEE_TIER_5.EMPLOYEE_ID = VISIT_DETAILS_ENHANCED_EDW.EMPLOYEE
LEFT JOIN ac_cloud.CALENDAR AS CALENDAR
    ON CAST(VISIT_DETAILS_ENHANCED_EDW.START_AT_UTC AS DATE) = CALENDAR.DATE
GROUP BY VISIT_DETAILS_ENHANCED_EDW.TENANT_UUID, VISIT_DETAILS_ENHANCED_EDW.TENANT, VISIT_DETAILS_ENHANCED_EDW.START_LAST_DAY_UTC,
         VISIT_DETAILS_ENHANCED_EDW.START_AT_UTC, VISIT_DETAILS_ENHANCED_EDW.EMPLOYEE, EMPLOYEE_TIER_5.EMPLOYEE_MAXIMUM_DAILY_CAPACITY,
         EMPLOYEE_TIER_5.EMPLOYEE_MAXIMUM_WEEKLY_CAPACITY, EMPLOYEE_TIER_5.EMPLOYEE_AVAILABILITY, CALENDAR.DATE

