SELECT
    VISIT_DETAILS_ENHANCED_EDW.TENANT_UUID,
    VISIT_DETAILS_ENHANCED_EDW.TENANT,
    VISIT_DETAILS_ENHANCED_EDW.START_LAST_DAY_UTC,
    CAST(VISIT_DETAILS_ENHANCED_EDW.START_AT_UTC AS DATE) AS DAY,
    VISIT_DETAILS_ENHANCED_EDW.EMPLOYEE,
    EMPLOYEE_TIER_5.EMPLOYEE_MAXIMUM_DAILY_CAPACITY,
    EMPLOYEE_TIER_5.EMPLOYEE_MAXIMUM_WEEKLY_CAPACITY,
    EMPLOYEE_TIER_5.EMPLOYEE_AVAILABILITY,
    IFF(IFNULL(EMPLOYEE_TIER_5.EMPLOYEE_MAXIMUM_DAILY_CAPACITY, 0) <> 0,
        EMPLOYEE_TIER_5.EMPLOYEE_MAXIMUM_DAILY_CAPACITY,
        EMPLOYEE_TIER_5.EMPLOYEE_MAXIMUM_WEEKLY_CAPACITY / 5) AS CALCULATED_DAILY_CAPACITY,
    COUNT(IFF(VISIT_DETAILS_ENHANCED_EDW.USAGE_FLAG = TRUE, VISIT_DETAILS_ENHANCED_EDW.VISIT_ID, NULL)) AS DAILY_VISITS_SCHEDULED,
    -- COUNT(DISTINCT CLIENT) AS DAILY_CLIENTS_SCHEDULED,
    SUM(IFF(VISIT_DETAILS_ENHANCED_EDW.USAGE_FLAG = TRUE, VISIT_DETAILS_ENHANCED_EDW.CALC_SCHED_HOURS, 0)) AS DAILY_SCHEDULED_HOURS,
    SUM(IFF(VISIT_DETAILS_ENHANCED_EDW.USAGE_FLAG = TRUE, VISIT_DETAILS_ENHANCED_EDW.CALC_SCHED_HOURS, 0)) - IFF(IFNULL(EMPLOYEE_TIER_5.EMPLOYEE_MAXIMUM_DAILY_CAPACITY, 0) <> 0,
        EMPLOYEE_TIER_5.EMPLOYEE_MAXIMUM_DAILY_CAPACITY,
        EMPLOYEE_TIER_5.EMPLOYEE_MAXIMUM_WEEKLY_CAPACITY / 5) AS EXCEEDING_OR_MISSING_HOURS
FROM ac_cloud.VISIT_DETAILS_ENHANCED_EDW AS VISIT_DETAILS_ENHANCED_EDW
LEFT JOIN AC_CLOUD_EDW.EMPLOYEE_TIER_5 AS EMPLOYEE_TIER_5
    ON VISIT_DETAILS_ENHANCED_EDW.TENANT_UUID = EMPLOYEE_TIER_5.TENANT_UUID
    AND EMPLOYEE_TIER_5.EMPLOYEE_ID = VISIT_DETAILS_ENHANCED_EDW.EMPLOYEE
LEFT JOIN ac_cloud.CALENDAR AS CALENDAR
    ON CAST(VISIT_DETAILS_ENHANCED_EDW.START_AT_UTC AS DATE) = CALENDAR.DATE
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8
